package com.example.cliqnotifier

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.database.Cursor
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.view.View
import android.widget.AdapterView
import android.widget.ArrayAdapter
import android.widget.Button
import android.widget.Spinner
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.cliqnotifier.adapters.TemplateAdapter
import com.example.cliqnotifier.databinding.ActivityMainBinding
import com.example.cliqnotifier.models.BankTemplate
import com.example.cliqnotifier.utils.TemplateGenerator
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding
    private val bankTemplatesList = mutableListOf<BankTemplate>()
    private lateinit var templateAdapter: TemplateAdapter

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        try {
            binding = ActivityMainBinding.inflate(layoutInflater)
            setContentView(binding.root)

            setupRecyclerView()
            loadSavedSettings()
            checkPermissions()

            binding.btnSave.setOnClickListener {
                saveSettings()
                Toast.makeText(this, "تم حفظ الإعدادات بنجاح!", Toast.LENGTH_SHORT).show()
            }

            binding.btnAddBankCard.setOnClickListener {
                showAddTemplateDialog()
            }
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(this, "خطأ في تشغيل الواجهة: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }

    private fun setupRecyclerView() {
        templateAdapter = TemplateAdapter(bankTemplatesList) { position ->
            if (position in bankTemplatesList.indices) {
                bankTemplatesList.removeAt(position)
                templateAdapter.notifyItemRemoved(position)
                saveSettings()
            }
        }
        binding.rvBankTemplates.layoutManager = LinearLayoutManager(this)
        binding.rvBankTemplates.adapter = templateAdapter
    }

    private fun checkPermissions() {
        try {
            val permissions = mutableListOf(
                Manifest.permission.RECEIVE_SMS,
                Manifest.permission.READ_SMS
            )
            
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                permissions.add(Manifest.permission.POST_NOTIFICATIONS)
            }

            val missingPermissions = permissions.filter {
                ContextCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED
            }

            if (missingPermissions.isNotEmpty()) {
                ActivityCompat.requestPermissions(this, missingPermissions.toTypedArray(), 101)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun showAddTemplateDialog() {
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_SMS) != PackageManager.PERMISSION_GRANTED) {
            Toast.makeText(this, "يرجى إعطاء صلاحية قراءة الرسائل أولاً", Toast.LENGTH_SHORT).show()
            checkPermissions()
            return
        }

        val dialogView = layoutInflater.inflate(R.layout.dialog_add_template, null)
        val spSenderList = dialogView.findViewById<Spinner>(R.id.spSenderList)
        val spSmsMessages = dialogView.findViewById<Spinner>(R.id.spSmsMessages)
        val tvAutoGeneratedTemplate = dialogView.findViewById<TextView>(R.id.tvAutoGeneratedTemplate)
        val btnCancel = dialogView.findViewById<Button>(R.id.btnCancel)
        val btnAdd = dialogView.findViewById<Button>(R.id.btnAddTemplate)

        val senders = getUniqueSmsSenders()
        val senderAdapter = ArrayAdapter(this, android.R.layout.simple_spinner_dropdown_item, senders)
        spSenderList.adapter = senderAdapter

        var currentSmsList = listOf<String>()
        var finalGeneratedPattern = ""

        spSenderList.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
            override fun onItemSelected(parent: AdapterView<*>?, view: View?, position: Int, id: Long) {
                if (position in senders.indices) {
                    val selectedSender = senders[position]
                    currentSmsList = getSmsMessagesForSender(selectedSender)
                    val smsAdapter = ArrayAdapter(this@MainActivity, android.R.layout.simple_spinner_dropdown_item, currentSmsList)
                    spSmsMessages.adapter = smsAdapter
                }
            }

            override fun onNothingSelected(parent: AdapterView<*>?) {}
        }

        spSmsMessages.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
            override fun onItemSelected(parent: AdapterView<*>?, view: View?, position: Int, id: Long) {
                if (currentSmsList.isNotEmpty() && position in currentSmsList.indices) {
                    val selectedSmsText = currentSmsList[position]
                    finalGeneratedPattern = TemplateGenerator.generateTemplateFromSms(selectedSmsText)
                    tvAutoGeneratedTemplate.text = finalGeneratedPattern
                }
            }

            override fun onNothingSelected(parent: AdapterView<*>?) {}
        }

        val dialog = AlertDialog.Builder(this)
            .setView(dialogView)
            .setCancelable(true)
            .create()

        btnCancel.setOnClickListener { dialog.dismiss() }

        btnAdd.setOnClickListener {
            val selectedSender = spSenderList.selectedItem?.toString() ?: ""

            if (selectedSender.isEmpty() || finalGeneratedPattern.isEmpty()) {
                Toast.makeText(this, "الرجاء اختيار مرسل ورسالة صحيحة", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            val newTemplate = BankTemplate(
                bankName = selectedSender,
                templatePattern = finalGeneratedPattern
            )

            bankTemplatesList.add(newTemplate)
            templateAdapter.notifyDataSetChanged()
            saveSettings()

            dialog.dismiss()
            Toast.makeText(this, "تم إضافة محفظة $selectedSender بنجاح!", Toast.LENGTH_SHORT).show()
        }

        dialog.show()
    }

    private fun getUniqueSmsSenders(): List<String> {
        val senders = mutableSetOf<String>()
        try {
            val smsUri = Uri.parse("content://sms/inbox")
            val cursor: Cursor? = contentResolver.query(smsUri, arrayOf("address"), null, null, "date DESC")

            cursor?.use { c ->
                val addressIndex = c.getColumnIndex("address")
                var count = 0
                while (c.moveToNext() && count < 100) {
                    if (addressIndex >= 0) {
                        val address = c.getString(addressIndex)
                        if (!address.isNullOrBlank()) {
                            senders.add(address)
                        }
                    }
                    count++
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return senders.ifEmpty { listOf("لا يوجد مرسلين") }.toList()
    }

    private fun getSmsMessagesForSender(senderName: String): List<String> {
        val messages = mutableListOf<String>()
        try {
            val smsUri = Uri.parse("content://sms/inbox")
            val cursor: Cursor? = contentResolver.query(smsUri, arrayOf("body", "address"), "address = ?", arrayOf(senderName), "date DESC")

            cursor?.use { c ->
                val bodyIndex = c.getColumnIndex("body")
                var count = 0
                while (c.moveToNext() && count < 10) {
                    if (bodyIndex >= 0) {
                        val body = c.getString(bodyIndex)
                        if (!body.isNullOrBlank()) {
                            messages.add(body)
                        }
                    }
                    count++
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return messages.ifEmpty { listOf("لا توجد رسائل لهذا المرسل") }
    }

    private fun saveSettings() {
        val prefs = getSharedPreferences("cliq_prefs", Context.MODE_PRIVATE)
        val gson = Gson()
        val jsonTemplates = gson.toJson(bankTemplatesList)

        prefs.edit().apply {
            putString("webhook_url", binding.etWebhookUrl.text.toString())
            putString("secret_token", binding.etSecretToken.text.toString())
            putBoolean("service_enabled", binding.switchService.isChecked)
            putString("bank_templates", jsonTemplates)
            apply()
        }
    }

    private fun loadSavedSettings() {
        try {
            val prefs = getSharedPreferences("cliq_prefs", Context.MODE_PRIVATE)
            binding.etWebhookUrl.setText(prefs.getString("webhook_url", ""))
            binding.etSecretToken.setText(prefs.getString("secret_token", ""))
            binding.switchService.isChecked = prefs.getBoolean("service_enabled", true)

            val jsonTemplates = prefs.getString("bank_templates", null)
            if (!jsonTemplates.isNullOrEmpty()) {
                val type = object : TypeToken<List<BankTemplate>>() {}.type
                val loaded: List<BankTemplate>? = Gson().fromJson(jsonTemplates, type)
                if (loaded != null) {
                    bankTemplatesList.clear()
                    bankTemplatesList.addAll(loaded)
                    templateAdapter.notifyDataSetChanged()
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
